<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SaySolTargetFramework Condition="'$(SaySolTargetFramework)' == ''">net10.0</SaySolTargetFramework>
    <TargetFramework>$(SaySolTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Tools/SpreadsheetImport/dotnet/SaySol.SerenityTools.SpreadsheetImport.csproj" />
  </ItemGroup>
</Project>
