<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SaySolTargetFramework Condition="'$(SaySolTargetFramework)' == ''">net8.0</SaySolTargetFramework>
    <TargetFramework>$(SaySolTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
